package email

import (
	"fmt"
	"html"
	"strings"
	"time"

	"github.com/mahype/update-watcher/checker"
	"github.com/mahype/update-watcher/notifier/formatting"
)

// BuildHTMLMessage creates an HTML email body from check results.
func BuildHTMLMessage(hostname string, results []*checker.CheckResult) string {
	summary := formatting.SummarizeResults(results)

	var b strings.Builder

	b.WriteString(`<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #333; max-width: 700px; margin: 0 auto; padding: 20px; }
  .header { background: #2563eb; color: white; padding: 16px 20px; border-radius: 8px 8px 0 0; }
  .header h2 { margin: 0; font-size: 18px; }
  .header p { margin: 4px 0 0; font-size: 13px; opacity: 0.85; }
  .content { border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 8px 8px; padding: 20px; }
  .section { margin-bottom: 20px; }
  .section h3 { font-size: 15px; margin: 0 0 8px; padding-bottom: 6px; border-bottom: 1px solid #e5e7eb; }
  table { border-collapse: collapse; width: 100%; font-size: 13px; }
  th { background: #f9fafb; text-align: left; padding: 8px 10px; border: 1px solid #e5e7eb; font-weight: 600; }
  td { padding: 6px 10px; border: 1px solid #e5e7eb; }
  .security td { background: #fef2f2; }
  .security .type-badge { color: #dc2626; font-weight: 600; }
  .type-badge { font-size: 12px; }
  .footer { margin-top: 20px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; }
  .security-banner { background: #fef2f2; border: 1px solid #fecaca; color: #991b1b; padding: 10px 16px; border-radius: 6px; margin-top: 16px; font-weight: 600; }
</style>
</head>
<body>
`)

	// Header
	b.WriteString(fmt.Sprintf(`<div class="header">
  <h2>%s Update Report: %s</h2>
  <p>Checked at %s | %d checkers | %d updates found</p>
</div>
<div class="content">
`, "\U0001f504", html.EscapeString(hostname),
		time.Now().UTC().Format("2006-01-02 15:04 UTC"), summary.CheckerCount, summary.TotalUpdates))

	// Per-checker sections
	for _, r := range results {
		icon := formatting.CheckerEmoji(r.CheckerName, true)
		displayName := formatting.CheckerDisplayName(r.CheckerName)

		b.WriteString(fmt.Sprintf(`<div class="section">
  <h3>%s %s — %s</h3>
`, icon, html.EscapeString(displayName), html.EscapeString(r.Summary)))

		if r.Error != "" {
			b.WriteString(fmt.Sprintf(`  <p style="color: #dc2626;">⚠️ %s</p>
`, html.EscapeString(r.Error)))
		}

		if len(r.Updates) > 0 {
			writeUpdatesTable(&b, r)
		}

		b.WriteString("</div>\n")
	}

	// Security banner
	if summary.SecurityCount > 0 {
		b.WriteString(fmt.Sprintf(`<div class="security-banner">⚠️ Security updates require attention (%d security updates)</div>
`, summary.SecurityCount))
	}

	// Footer
	b.WriteString(`<div class="footer">Generated by update-watcher</div>
</div>
</body>
</html>`)

	return b.String()
}

func writeUpdatesTable(b *strings.Builder, r *checker.CheckResult) {
	isWP := r.CheckerName == "wordpress"

	b.WriteString("  <table>\n    <tr>")
	if isWP {
		b.WriteString("<th>Site</th><th>Type</th>")
	}
	b.WriteString("<th>Package</th><th>Current</th><th>New</th><th>Type</th></tr>\n")

	for _, u := range r.Updates {
		rowClass := ""
		if u.Type == checker.UpdateTypeSecurity {
			rowClass = ` class="security"`
		}

		b.WriteString(fmt.Sprintf("    <tr%s>", rowClass))
		if isWP {
			b.WriteString(fmt.Sprintf("<td>%s</td>", html.EscapeString(u.Source)))
			typeName := strings.ToUpper(u.Type[:1]) + u.Type[1:]
			b.WriteString(fmt.Sprintf("<td>%s</td>", html.EscapeString(typeName)))
		}
		if u.Type == checker.UpdateTypeSecurity {
			b.WriteString(fmt.Sprintf("<td><strong>%s</strong></td>", html.EscapeString(u.Name)))
		} else {
			b.WriteString(fmt.Sprintf("<td>%s</td>", html.EscapeString(u.Name)))
		}
		b.WriteString(fmt.Sprintf("<td>%s</td>", html.EscapeString(u.CurrentVersion)))
		b.WriteString(fmt.Sprintf("<td>%s</td>", html.EscapeString(u.NewVersion)))

		if u.Type == checker.UpdateTypeSecurity {
			b.WriteString(fmt.Sprintf(`<td><span class="type-badge">⚠️ %s</span></td>`, html.EscapeString(u.Type)))
		} else {
			b.WriteString(fmt.Sprintf("<td>%s</td>", html.EscapeString(u.Type)))
		}
		b.WriteString("</tr>\n")
	}

	b.WriteString("  </table>\n")
}
